### ISSUE TITLE
Suddenly changing mouse sensitivity after launching dota 2 with vulkan api on Arch Linux /Debian Linux or launching Dota 2 with opengl and streaming/recording via ffmpeg and obs with vaapi encoder

### ISSUE THREAD

**Issue by koreanfan** [daniel-schuermann/mesa#184] opened 2020-06-12 21:33 UTC
Please run with "RADV_PERFTEST=llvm" (or drop "RADV_PERFTEST=aco" if you need that to enable ACO) to disable ACO and confirm that the issue is specific to ACO.

**Describe the bug**
Launch Dota 2 with vulkan api. After dota 2 main menu shows up, a few seconds later (5-7 seconds) mouse sensitivity suddenly changing without user prompt. When you alt tab and recheck mouse sensitivity settings in terminal via xinput list-props id , they shown sames as before, but mouse sensitivity is different. So i use xinput set-prop id .. for changing mouse sensitivity to previous (was before launching dota 2 with vulkan) value , but again after alt tabbing to dota 2 main menu, a few seconds later mouse sensitivity changing again without user prompt. With opengl renderer there were no issue. But if you use opengl renderer and streaming/recording via ffmpeg or obs with vaapi encoder you have the same issue. Mouse settings:
xinput list-props 12
Device ' USB OPTICAL MOUSE':
	Device Enabled (146):	1
	Coordinate Transformation Matrix (148):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
	libinput Natural Scrolling Enabled (281):	0
	libinput Natural Scrolling Enabled Default (282):	0
	libinput Scroll Methods Available (283):	0, 0, 1
	libinput Scroll Method Enabled (284):	0, 0, 0
	libinput Scroll Method Enabled Default (285):	0, 0, 0
	libinput Button Scrolling Button (286):	2
	libinput Button Scrolling Button Default (287):	2
	libinput Button Scrolling Button Lock Enabled (288):	0
	libinput Button Scrolling Button Lock Enabled Default (289):	0
	libinput Middle Emulation Enabled (290):	0
	libinput Middle Emulation Enabled Default (291):	0
	libinput Accel Speed (292):	-1.000000
	libinput Accel Speed Default (293):	0.000000
	libinput Accel Profiles Available (294):	1, 1
	libinput Accel Profile Enabled (295):	1, 0
	libinput Accel Profile Enabled Default (296):	1, 0
	libinput Left Handed Enabled (297):	0
	libinput Left Handed Enabled Default (298):	0
	libinput Send Events Modes Available (266):	1, 0
	libinput Send Events Mode Enabled (267):	0, 0
	libinput Send Events Mode Enabled Default (268):	0, 0
	Device Node (269):	"/dev/input/event13"
	Device Product ID (270):	0, 1336
	libinput Drag Lock Buttons (299):	<no items>
	libinput Horizontal Scroll Enabled (300):	1
I tested many linux distributions and try to use different versions of mesa but its didnt help
**Screenshots**
For rendering errors, please insert screenshots showing incorrect rendering (ACO) and correct rendering (LLVM).

**RenderDoc capture:**
Please try to link to a RenderDoc capture of the issue, using either the ACO or LLVM compiler for this is fine. Once RenderDoc is installed, a capture can be created by:

- setting the environment variable ENABLE_VULKAN_RENDERDOC_CAPTURE to "1"
- pressing F12 once the problem is visible (or for hangs, would be visible if ACO was used)
- uploading the .rdc file created in /tmp/renderdoc

For Steam, the ENABLE_VULKAN_RENDERDOC_CAPTURE can be set by setting the game's launch options to "ENABLE_VULKAN_RENDERDOC_CAPTURE=1 %command%", possibly including "RADV_PERFTEST=llvm" at the beginning if you want LLVM to be used. You'll want to change the launch options back to what they were before once you've finished.

An alternative method is to close Steam and start it from the console via "ENABLE_VULKAN_RENDERDOC_CAPTURE=1 steam" and run the game.

**System information:**
 - GPU: [e.g. Radeon RX480] RX560
 - ACO version: [either git commit/branch or package version] All recent versions

**Additional context**

**Comment by Venemo** [comment] 2020-06-15 13:05
Thanks for the bug report. Are you certain that this issue happens only with ACO and not the LLVM backend?

**Comment by koreanfan** [comment] 2020-06-15 13:13
This issue happens with aco and llvm

**Comment by Venemo** [comment] 2020-06-15 13:28
The fact that it happens with both compilers, and that you can trigger it with even the OpenGL renderer, would suggest that it's a game bug, and not a shader compiler bug.

**Comment by koreanfan** [comment] 2020-06-15 13:35
This issue happens with opengl if i only use ffmpeg or obs with vaapi encoder. If i use software encoder there were no problems.

**Comment by Venemo** [comment] 2020-06-15 14:09
Yes, I understand that the problem only happens under specific circumstances, and I also respect that it is very frustrating to you. It is however very likely to be a game bug and not a driver bug. And it is clearly not a bug in the shader compiler.

I see you already opened an issue for the Dota team here: https://github.com/ValveSoftware/Dota-2/issues/1770 ― that is where this issue should be tracked.

**Comment by daniel-schuermann** [comment] 2020-06-15 14:32
Closed as this will be handled at the Dota2 issue tracker.

**Closed as completed by daniel-schuermann** 2020-06-15 14:32 UTC

**Comment by koreanfan** [comment] 2020-06-28 20:05
I have tested dota 2 with amdgpu-pro drivers on CentOS 8.2 (with pro opengl and pro vulkan) and there were no issue with suddenly changing mouse sensitivity. But when i used mesa drivers on CentOS 8.2 i hade this issue. So i think this is mesa driver problem.

**Comment by Venemo** [comment] 2020-06-29 07:02
Then please open a bug in the mesa bug tracker
