### ISSUE TITLE
Grand Theft Auto V Lighting Corruption (Intense bloom, overblown light)

### ISSUE THREAD

**Issue by Xunderground** [daniel-schuermann/mesa#151] opened 2019-10-13 21:47 UTC
**Describe the bug**
When running GTA V in Direct3D11 mode and using the ACO compiler (even with the vertex shaders being passed on to LLVM), the lighting in GTA V is overblown during certain times of day. You can test this using the ingame benchmark.

**Screenshots**
![Screenshot of incorrect ACO behavior](https://user-images.githubusercontent.com/56520011/66722376-c1b48f00-edda-11e9-8d8a-d1be7608b683.png)
![Screenshot of behavior under LLVM](https://user-images.githubusercontent.com/56520011/66722935-89647f00-ede1-11e9-9c99-2681b9a446d2.png)

**RenderDoc capture:**

I attempted to capture a RenderDoc, but upon starting the capture, GTA V hard freezes and doesn't recover. I attempted to attach the renderdoc but it is over a gigabyte in size, and I'm not sure if that's correct. I can provide this file, or if anyone can direct me through possible troubleshooting for why it didn't work, I'm happy to try again.

**System information:**
 - GPU: [ASUS ROG Strix AMD RX570 OC]
 - ACO version: Mesa 19.3.0-devel (git-1b2cbc98c3)

**Additional context**
GTA V is installed via Lutris install script, using DXVK (though the problem persists using Wine's built in D3D11 solution), and only occurs on the Direct3D11 backend.

**Comment by daniel-schuermann** [comment] 2019-10-14 08:41
This seems to be the same issue as https://github.com/daniel-schuermann/mesa/issues/148.
The size of your renderdoc capture seems normal to me. It also takes a while to capture while the screen freezes. You can test if your capture works and also reproduces the issue by opening it using `qrenderdoc` once with RADV_PERFTEST=aco and once with RADV_PERFTEST=llvm. If the capture shows the issue only with aco, please upload it somewhere and link it.

**Comment by brunibunny** [comment] 2019-10-20 06:11
I'm facing the same issue. Let me know if a RenderDoc from me would be of any help.

**Comment by daniel-schuermann** [comment] 2019-12-05 11:33
closed as duplicate of https://github.com/daniel-schuermann/mesa/issues/148.
@Xunderground I would appreciate if you can confirm that this issue has been fixed. Thx

**Closed as completed by daniel-schuermann** 2019-12-05 11:33 UTC
