### ISSUE TITLE
worse performance vs. llvm & amdvlk in compute shader raytracing synthie

### ISSUE THREAD

**Issue by aufkrawall** [daniel-schuermann/mesa#86] opened 2019-07-29 14:07 UTC
The 8x8 register version scores ~700fps minimum with llvm, while it's ~640fps with aco. Latest amdvlk-open scores ~900fps. This is on RX 570.
I tried to create a RD capture, but it didn't work (neither on Windows with 32 bit RD version).

Binaries are attached. They are runtime packed and thus like to trigger AVs, which is why there is password protection for the archive (PW "csrt").
[csrt.zip](https://github.com/daniel-schuermann/mesa/files/3442624/csrt.zip)
You need DXVK and perhaps other lib32 dependencies.

**Comment by baryluk** [comment] 2019-10-04 22:26
This zip file looks to be malformed or using some weird compression.

Could you upload tar.gz instead please?

**Comment by pendingchaos** [comment] 2019-10-04 22:31
[csrt.tar.gz](https://github.com/daniel-schuermann/mesa/files/3692523/csrt.tar.gz)

**Comment by pendingchaos** [comment] 2019-10-04 22:47
I can run the application and can reproduce the performance issue

**Comment by baryluk** [comment] 2019-10-04 23:02
For 8x8 version, using Mesa master branch (git-ce76be9933, plus some extra not yet merged NIR patches) with LLVM 10~svn372920, Wine Staging 4.12.1, DXVK 1.4.1, and MS' d3dcompiler_43.dll, AMD Fury X (FIJI), I am getting 900 fps for both LLVM and ACO. LLVM is however slightly faster, ACO takes about 1.12ms on average per frame, and LLVM takes about 1.08ms per frame.

![csrt](https://user-images.githubusercontent.com/110322/66245052-ee8de580-e6fa-11e9-8782-588860ba6fc8.png)

**Comment by pendingchaos** [comment] 2020-01-30 14:24
NIR's GCM optimization pass (even with global value numbering disabled) seems to help.

**Comment by Venemo** [comment] 2023-05-17 15:28
Hi,

This repo is no longer being maintained since ACO was merged in upstream Mesa since late 2019. If you have issues with it, please open an issue in upstream Mesa here: https://gitlab.freedesktop.org/mesa/mesa/-/issues - select the Radeon Vulkan bug report template and fill out the details.

**Closed as completed** 2023-05-17 16:10 UTC
Labels: Performance, Polaris
