### ISSUE TITLE
A Plague Tale: Innocence -> *** stack smashing detected ***: <unknown> terminated

### ISSUE THREAD

**Issue by marhkb** [daniel-schuermann/mesa#174] opened 2020-01-12 13:24 UTC
Using the latest build (20.0.0_devel.20200107.7b444ba5ef1-7) provided by valveaur in Arch Linux crashes the mentioned game for me. The game starts fine but on loading a save game it crashes me back to Desktop. It used to work with aco. RADV_PERFTEST=llvm is still fine.

**RenderDoc capture:**
Not sure if this is the right tool as it only captures a single "frame" as far I understand but I might be wrong.

**System information:**
 - distribution: Arch Linux
 - GPU: RX 5700 XT
 - ACO version: 20.0.0_devel.20200107.7b444ba5ef1-7 provided by valveaur repo
 - dxvk: tried several versions but to no avail
 - wine: tried several versions but to no avail

If there is no clue what may cause this issue I could help trying to bisect. But I am not sure if I find time to this in the next days. 

EDIT: typos

**Comment by daniel-schuermann** [comment] 2020-01-12 14:58
Can you test with latest upstream master? If the issue is the one I think it is, it should be resolved with https://gitlab.freedesktop.org/mesa/mesa/merge_requests/3320 .
I can rebase this repository, tomorrow. A bit strange as you should get the same error with LLVM, but well.

**Comment by marhkb** [comment] 2020-01-12 15:18
You are right. Latest master again works with aco. Thank you.

**Comment by daniel-schuermann** [comment] 2020-01-15 15:04
should be resolved now.

**Closed as completed by daniel-schuermann** 2020-01-15 15:04 UTC
