### ISSUE TITLE
Killing Floor 2: Bugged Lighting

### ISSUE THREAD

**Issue by 0x8080** [daniel-schuermann/mesa#146] opened 2019-09-30 03:23 UTC
**Describe the bug**
Some static lighting not rendering properly resulting in incorrect lighting or at worst a completely black scene

**Screenshots**
ACO Output:
![20190929144509_1](https://user-images.githubusercontent.com/14355117/65847350-712f3300-e2fe-11e9-8031-a9b4ba57811b.jpg)

LLVM  Output:
![20190929144127_1](https://user-images.githubusercontent.com/14355117/65847502-09c5b300-e2ff-11e9-813d-6887d7c33246.jpg)

LLVMVS Output:
![20190929145031_1](https://user-images.githubusercontent.com/14355117/65847377-8ad07a80-e2fe-11e9-9ea6-d3dea1d44195.jpg)

**System information:**
 - GPU: RX 580 on MESA git ffb0d3a25c60dd7fc5cb1f2c33c2977b245b5fee
 - ACO version: From the latest MESA master git at the time ffb0d3a25c60dd7fc5cb1f2c33c2977b245b5fee

**Additional context**
Tested on map Killing Pool (KF-KillingPool)

**Comment by daniel-schuermann** [comment] 2019-10-11 14:48
As I cannot reproduce this issue with other captures I have from this game, would you be able to provide a renderdoc capture of the scene?

**Comment by AwesamLinux** [comment] 2019-10-11 19:40
**System Information**
- GPU: RX VEGA 56
- GPU Driver: 19.1.0+aco+git1570636576-246f50f2c13-1bionic1 (Valves PPA)
- Kernel version:  5.4.0-050400rc2-lowlatency
- Distro version: Linux Mint 19.2 Tina (64 bit) (Cinnamon)
- Proton version: 4.11-7

[system_info.txt](https://github.com/daniel-schuermann/mesa/files/3719369/system_info.txt)
[steam-232090.log.zip](https://github.com/daniel-schuermann/mesa/files/3719371/steam-232090.log.zip)


**Testing Report**

I tried this map (KF-KillingPool) (https://steamcommunity.com/sharedfiles/filedetails/?id=1210703659). I'm unable to replicate the issue, this looks accurate to me:

LLVM:
![llvm](https://user-images.githubusercontent.com/43387963/66679712-2357ea80-ec6f-11e9-9e4e-d36a6188b954.jpg)

ACO:
![aco](https://user-images.githubusercontent.com/43387963/66679709-205cfa00-ec6f-11e9-8492-4a719b9b8112.jpg)

![20191011214450_1](https://user-images.githubusercontent.com/43387963/66680288-7d0ce480-ec70-11e9-8779-45df999f537c.jpg)


Maybe this got already fixed in the recent driver update (or maybe this is just a Polaris specific issue).

**RenderDoc capture:**
Renderdoc 1.4 capture of this scene using ACO below:
https://drive.google.com/open?id=1LlK4NiMwNo8Mo3Iw-vxbNgfxGD6Gd6Wd

**Comment by daniel-schuermann** [comment] 2019-10-23 06:42
@0x8080 Is this issue still present for you? If so, could you please provide a renderdoc capture of the scene, otherwise I'd like to close the issue.

**Comment by daniel-schuermann** [comment] 2019-10-31 10:12
Closed because it seems abandoned.

**Closed as completed by daniel-schuermann** 2019-10-31 10:12 UTC
Labels: Polaris, Corruption

**Comment by 0x8080** [comment] 2019-12-04 12:24
Sorry, this issue has been fixed for me since I last tried it

**Comment by daniel-schuermann** [comment] 2019-12-04 12:25
No worries and thx for reporting anyway :)
