### ISSUE TITLE
GTA V Graphical issues

### ISSUE THREAD

**Issue by Kirottu** [daniel-schuermann/mesa#148] opened 2019-10-10 12:41 UTC
With the DX11 renderer GTA V's light levels are absurdly high making the game unplayable, but with DX10 that issue doesn't appear.

**Comment by Clifforus** [comment] 2019-10-10 17:54
I'm having the same issue. Can confirm that it doesn't happen in DX10 mode, or with `RADV_PERFTEST=llvm`.

**Comment by daniel-schuermann** [comment] 2019-10-10 18:41
Would any of you two maybe be able to provide some additional information like requested when opening a bug report?
https://github.com/daniel-schuermann/mesa/issues/new?template=bug_report.md

**Comment by Clifforus** [comment] 2019-10-10 21:13
Description:

All lighting in the game appears extremely bright and overexposed. Light areas appear to blend into a mess of white, and darker areas appear very pale. Seems to be unaffected by changing graphics options (other than running in DX10 mode).

Screenshots:

With ACO
![aco-render](https://user-images.githubusercontent.com/42838666/66605570-381d7b00-eba8-11e9-8cd9-b6ffdc2a9a69.png)

With LLVM
![llvm-render](https://user-images.githubusercontent.com/42838666/66605602-466b9700-eba8-11e9-8097-3dfa60a578c1.png)


RenderDoc capture: https://drive.google.com/open?id=1M0R8NqHIw0196p8WcYPkdWC8WJ8UUZMr

System Information:

GPU: 8GB Sapphire RX480 Nitro+
ACO version: git-6c3bad5214 (mesa-aco-git from Valve's Arch repository)

**Comment by guustflater** [comment] 2019-10-23 16:52
Same here

**Comment by win8linux** [comment] 2019-11-11 07:25
It also occurs on a 5700 XT, so it might not be exclusive to just Polaris alone (Mesa-ACO from xxmitsu's Fedora repo):
![Screenshot_20191111_140141](https://user-images.githubusercontent.com/11584387/68568764-72c04f00-0497-11ea-9184-5c44f8e6bcba.png)

**Comment by pendingchaos** [comment] 2019-11-11 10:36
I can reproduce it

Happens with Vega too

I'm not entirely certain, but I also reproduced with with a version of ACO which should have worked with GTA V. So I'm guessing it's a DXVK or game update exposing an ACO bug and not an ACO regression

**Comment by pendingchaos** [comment] 2019-11-11 20:43
(when I said "I can reproduce it", I meant "I could reproduce it not that long ago")

The start of the benchmark seems to look fine to me now, without any lighting issues

**Comment by ghost** [comment] 2019-12-04 20:07
In addition to this issue, I am experiencing a significant drop in performance in the game, just as the author of the above-mentioned issue. It runs worse than during my initial testing around the time ACO testing instructions were publicized, and when using LLVM instead.

**Comment by pendingchaos** [comment] 2019-12-04 20:43
@Bryophyllum: what ACO version and/or package and DXVK version are you using?

I can reproduce this issue with an old version of ACO but the latest upstream version of ACO and the one from this Github repository seems to work fine (this is with Proton 4.11/DXVK 1.4.2)

**Comment by ghost** [comment] 2019-12-04 21:24
@pendingchaos I am using [the mesa-aco extension for the 19.08 version of the freedesktop runtime](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/tree/19.08/elements/extensions/mesa-aco), in whose buildfile [this repository](https://gitlab.com/freedesktop-sdk/mirrors/mesa-aco) is referenced; and DXVK 1.4.6 alongside Proton 4.11 on Flatpak Lutris.

It looks like I have confused rebuilds of the extension with actual updates for its codebase; I have been under the impression that the freedesktop project's mirror of this repository was up-to-date. And since this issue and the other one in this repository have remained open, I assumed that this graphical issue has not been fixed.

Either way, I have notified freedesktop maintainers of necessity to update the mirror and the extension.

**Comment by Slyfox88** [comment] 2019-12-31 21:46
I'm still having this issue after updating Mesa to version 19.3.1. I assume this includes a much newer version of ACO than the 19.2.1 version I was running before. Any ideas?

![GTA5s](https://user-images.githubusercontent.com/58151689/71634717-4c43a800-2bec-11ea-8b6a-495a15064e0c.png)

OS: Ubuntu 19.10
KERNEL: 5.3.0-24-generic
CPU: AMD Ryzen 5 2600X Six-Core
GPU: Radeon RX Vega
GPU DRIVER: Mesa 19.3.1
RAM: 16 GB
WINE BUILD: wine-5.0-rc3 (Staging)
DXVK VERSION: 1.5.0

**Comment by andrew-mcmahon** [comment] 2020-01-04 12:27
As much as I've tried, I can't seem to reproduce this problem on my R9 285 (TONGA/GCN3)
The worst problem I've seen is an [over saturated mobile phone](https://imgur.com/a/CdxuScT) which I [posted about here](https://github.com/ValveSoftware/Proton/issues/37#issuecomment-570550367) - at the time I was using Mesa 19.3.1 with ACO.  
  
I've switched over to this Mesa fork now (Mesa 20.0.0-devel (git-3409c06e26)) and I'll see if it happens again. For the most part the game appears to work perfectly with [Proton-4.21-GE-2](https://github.com/GloriousEggroll/proton-ge-custom/releases).  
I took a [bunch of screenshots](https://steamcommunity.com/id/mwnn85/screenshots/); as a bonus any sort of stuttering has been completely eliminated. [~~V-Sync currently seems a bit wonky~~ fixed with latest DXVK commits.](https://github.com/doitsujin/dxvk/issues/1314)

I used RenderDoc to [grab a few captures](https://drive.google.com/open?id=13ey4mnOMdT2Ozwwc15c1xnuDoq4E0L2H) (6GB extracted) - have a look at those if you wish - I don't see much wrong with them.
It's not much fun playing GTA V at 8 fps instead of 30-100+ fps :D

Debian Testing
Linux debian 5.4.7-custom #1 SMP Tue Dec 31 20:47:27 GMT 2019 x86_64 GNU/Linux
Phenom II X4 955 { ...yes I really am still using a 2009 Phenom II :'( }
Sapphire R9 285 2GB
Mesa 20.0.0-devel (git-3409c06e26) [mesa build options](https://gist.github.com/andrew-mcmahon/59117fff714ee6c0e817f3c631f384da)
LLVM 9
[AMDGPU firmware 20191215](https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/)
Proton-4.21-GE-2 
[GTA V settings ](https://gist.github.com/andrew-mcmahon/682d489c79e2346a9ddf8b70266c9bda)
[glxinfo](https://gist.github.com/andrew-mcmahon/aa7a45be49d6da46cdeeb3171af6c9dd)
[steam system info](https://gist.github.com/andrew-mcmahon/7dedc63216715cbcf8225da226a2da5e)

Will this fork continue to receive updates or has all the work been merged back into the main repository at [Gitlab](https://gitlab.freedesktop.org/mesa/mesa)?  
If I do see this occur then I'll post again but it hasn't so far with 27 hours of play.

**Comment by daniel-schuermann** [comment] 2020-01-07 11:04
> Will this fork continue to receive updates or has all the work been merged back into the main repository at [Gitlab](https://gitlab.freedesktop.org/mesa/mesa)?
> If I do see this occur then I'll post again but it hasn't so far with 27 hours of play.

Thx for the effort! This repository will continue to see occasional updates. (We try to rebase about once per week, but I have been away the last month.)
So, normally this repository is roughly up-to-date with mesa master + some not yet merged MRs. We might fade-out the repository with mesa 20.0, though.

**Comment by andrew-mcmahon** [comment] 2020-01-19 12:07
So about a 100 (yikes!) hours later I've finished all the single player stuff and obtained the [rare achievements](https://steamcommunity.com/id/mwnn85/stats/271590/achievements/).  
Nothing bad to report really just the odd minor graphical oddity; some have already been solved just by keeping up-to-date. Probably makes more sense to point those out once ACO is feature-complete - this experimental stuff is fast moving.
  
Compiling mesa from the master branch here, Proton 4.21-GE-2 + DXVK master branch i.e:
```
/home/mwnn/.steam/debian-installation/compatibilitytools.d/Proton-4.21-GE-2/dist/lib/wine/dxvk/
/home/mwnn/.steam/debian-installation/compatibilitytools.d/Proton-4.21-GE-2/dist/lib64/wine/dxvk/
```  
Standard Proton doesn't quite work perfectly with GTA V yet & DXVK master has a nice V-Sync fix.  
Just wondering if anyone can replicate this strange issue with the [GTA ONLINE character creation;](https://imgur.com/a/ivVVzjT) truth be told I'm a bit hesitant to use Renderdoc on the online-side of the game.  
  
Again GTA ONLINE appears to work very well - reached Rank 15.  
Quite amazing what you clever bunch are doing; I like to think that within the next 5 years or so this should all be idiot-proof. There weren't any Linux drivers at all for my R9 285 on release (~2014) and look where we are now. I don't see any reason to use Windows ever again - wiped that off a year ago and would've done so earlier.

**Comment by Venemo** [comment] 2020-02-11 11:40
Can you guys confirm that this issue has been solved?

**Comment by andrew-mcmahon** [comment] 2020-02-12 11:57
I'll give you my thoughts for what it's worth; I'm only seeing a few niggling issues with the game. I've 100% the single player and have [finished most parts of the ONLINE aspect](https://imgur.com/a/kS4K6a8) of the game including each approach on the Casino heist - with a few million in the bank _(not in real life unfortunately :P)_
  
1> There's still a few graphical oddities on character models in GTA ONLINE when using ACO (https://imgur.com/a/ivVVzjT). _I should be able to capture some RenderDoc traces for these now_  
2> Occasionally the in-game phone appears [to be over saturated](https://imgur.com/a/CdxuScT) - I've never seen the whole screen become affected like the earlier posts above. _Again I'll try to capture that._  
3> The in-game Graphical settings menu can be a strange when applying new settings and/or restarting.
4> Anything other than **Proton-4.21-GE-2** leaves behind a bunch of zombie processes and other nonsense. That includes the recently released _Proton-5.1-GE-1_ and _Proton 5.0-1_. The game is still shown as running until all of those are found and killed off. Particularly irritating.
5> The Rockstar Social Club UI suffers from a [missing mouse cursor](https://github.com/ValveSoftware/Proton/issues/168); there's obviously something funny going on with how WINE handles overlays. I'd recommend using the Steam Overlay whilst in-game to chat with friends if possible as that works perfectly (SHIFT+TAB)  
  
I've got a lot more firepower now - gone from a Phenom II x4 955 to a Ryzen 3700X!  
Using ACO I get a straight 60fps @ 1080p without any stuttering with all the settings on High; my R9 285 only has 2GB of VRAM so I'm forced to normal texture detail unfortunately. Once it's stable a RX 5700 would be nice jump when the prices come down.
[lscpu.txt](https://github.com/daniel-schuermann/mesa/files/4191846/lscpu.txt), [glxinfo.txt](https://github.com/daniel-schuermann/mesa/files/4191845/glxinfo.txt), [Debian Testing + latest stable kernel](https://github.com/daniel-schuermann/mesa/files/4191879/uname.txt)

**Comment by pendingchaos** [comment] 2020-02-12 12:01
I'm not sure a renderdoc capture would be useful. IIRC they seem to always just be a image copy without capturing the actual commands for the frame

**Comment by pendingchaos** [comment] 2020-02-12 12:02
I have the game, so maybe I could try to reproduce the character model issue once I get it working again

**Comment by andrew-mcmahon** [comment] 2020-02-12 12:04
Is there anything that I could provide that would be useful Rhys?  
Some more [images](https://imgur.com/a/R8cjFoI).

**Comment by Venemo** [comment] 2023-05-17 15:28
Hi,

This repo is no longer being maintained since ACO was merged in upstream Mesa since late 2019. If you have issues with it, please open an issue in upstream Mesa here: https://gitlab.freedesktop.org/mesa/mesa/-/issues - select the Radeon Vulkan bug report template and fill out the details.

**Closed as completed** 2023-05-17 16:10 UTC
Labels: Vega, Polaris, Corruption, Navi
