### ISSUE TITLE
Quantum Break has graphics artifacts with ACO compiler

### ISSUE THREAD

**Issue by NTMan** [daniel-schuermann/mesa#69] opened 2019-07-09 22:25 UTC
[Quantum Break](https://store.steampowered.com/app/474960/) has graphics artifacts with ACO compiler, but LLMV is an artifact free.
Tested on commit 9928a225 with AMD Radeon VII.
Demonstration: https://youtu.be/R2EDo4OvV7k

Here compressed save folder: [QuantumBreak.zip](https://github.com/daniel-schuermann/mesa/files/3375580/QuantumBreak.zip)
Extracted save folder should be placed in `~/.steam/steam/steamapps/compatdata/474960/pfx/drive_c/users/steamuser/Local Settings/Application Data`

Unfortunately, the game couldn't launch with the option `ENABLE VULKAN RENDERDOC CAPTURE=1` so I unable create a trace file for the issue.

```
$ inxi -bM
System:    Host: localhost.localdomain Kernel: 5.2.0-0.rc7.git1.1.fc31.x86_64 x86_64 bits: 64 Desktop: Gnome 3.33.3 
           Distro: Fedora release 31 (Rawhide) 
Machine:   Type: Desktop Mobo: ASUSTeK model: ROG STRIX X470-I GAMING v: Rev 1.xx serial: <root required> 
           UEFI: American Megatrends v: 2406 date: 06/21/2019 
CPU:       8-Core: AMD Ryzen 7 2700X type: MT MCP speed: 2944 MHz min/max: 2200/3700 MHz 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Vega 20 [Radeon VII] driver: amdgpu v: kernel 
           Display: wayland server: Fedora Project X.org 1.20.5 driver: amdgpu resolution: 3840x2160~60Hz 
           OpenGL: renderer: AMD Radeon VII (VEGA20 DRM 3.32.0 5.2.0-0.rc7.git1.1.fc31.x86_64 LLVM 8.0.0) 
           v: 4.5 Mesa 19.2.0-devel 
Network:   Device-1: Intel I211 Gigabit Network driver: igb 
           Device-2: Realtek RTL8822BE 802.11a/b/g/n/ac WiFi adapter driver: rtw_pci 
Drives:    Local Storage: total: 11.57 TiB used: 10.14 TiB (87.6%) 
Info:      Processes: 454 Uptime: 6h 37m Memory: 31.29 GiB used: 15.93 GiB (50.9%) Shell: bash inxi: 3.0.34 
```

**Comment by SR-dude** [comment] 2019-07-17 20:00
This game is currently on sale for $10 at amazon.
You get a steam key. That may not be needed for
mesa coders.  So, I picked it up. I'll try it out and
 get back in a day or two.

**Comment by daniel-schuermann** [comment] 2019-07-20 14:10
Any success?

**Comment by NTMan** [comment] 2019-07-20 14:13
> Any success?

What should I do?

**Comment by SR-dude** [comment] 2019-07-20 14:19
I manage to capture some renderdocs with the steam version. Links
are forthcoming. I'm currently running the game with wine version
4.12.1, no staging patches.  No steamplay in play here. There were
problems with the mouse thus making the game unplayable, but 
irrelevant. I tried NTMan saves, but they were unsuitable because,
I don't know how to play and the previously mentioned control 
problems. Behind me it was pitch dark and in front of me there were
bad guys with guns  that killed me right on the spot. Thus, I 
couldn't explore the room.

Additionally, the biggest problem was the crashes. Disabling the steam
overlay didn't help. I'll have to try some different wine versions to
see if I can fix this.

With Frame 2, where it says: 'Meyer Physics Research Center', you'll
see a rectangular box that encompasses the lettering. That box 
flashes. Right below the word 'Meyer', you'll look closely and it
reads: 'Riverport University'. There is another dark box with a slanted
top side. That box flashes as well.

Links are on the way. Below is  one of the crashes provided by wine.
I'll try to get some wine console output if indeed this is d3d/vulkan 
related.

+
LINKS

Frame 1
https://drive.google.com/open?id=1LkyDlZ3mHeEomdASSPuYXEhK0zhYyqjE

Frame 2
https://drive.google.com/open?id=138f_x-0k3jEvkxMsU3rxIrn61CgR0x2V

**Comment by SR-dude** [comment] 2019-07-20 14:21
Unhandled exception: page fault on write access to 0x07f6f000 in 64-bit code (0x0000000006a7238c).
Register dump:
 rip:0000000006a7238c rsp:000000003091f1a8 rbp:000000003091f2e0 eflags:00010202 (  R- --  I   - - - )
 rax:0000000007f50608 rbx:0000000006c7fae0 rcx:0000000007f6f070 rdx:00000000289b053c
 rsi:000000000545d413 rdi:000000003091f510  r8:00000000000005f0  r9:000000000000000b r10:000000003091f510
 r11:0000000007f6efd4 r12:0000000000000000 r13:000000001f2dfa30 r14:0000000000000060 r15:0000000000000010
Stack dump:
0x000000003091f1a8:  0000000006a3c24d 000000000545d413
0x000000003091f1b8:  00000000000700ea 000000000545d413
0x000000003091f1c8:  00000000230c0780 00000000230c0780
0x000000003091f1d8:  0000000006a6047d 00000000000700ea
0x000000003091f1e8:  000000003091f2e0 000000000545d413
0x000000003091f1f8:  0000000000000000 0000000000000384
0x000000003091f208:  0000000000000060 0000000000000001
0x000000003091f218:  0000000000000640 000000001f2dfa30
0x000000003091f228:  0000006000000000 0000000000000384
0x000000003091f238:  0000006000000000 000000004d430003
0x000000003091f248:  0000000000000000 0000000000000000
0x000000003091f258:  0000038400000640 0000000000000000
Backtrace:
=>0 0x0000000006a7238c EntryPoint+0x117c() in gameoverlayrenderer64 (0x000000003091f2e0)
  1 0x0000000006a3c24d EntryPoint+0xffffffffffffffff() in gameoverlayrenderer64 (0x000000003091f2e0)
  2 0x0000000006a6047d EntryPoint+0xffffffffffffffff() in gameoverlayrenderer64 (0x000000003091f2e0)
0x0000000006a7238c EntryPoint+0x117c in gameoverlayrenderer64: movaps	%xmm1,0xffffffffffffff90(%rcx)
Modules:
Module	Address					Debug info	Name (224 modules)
PE	          250000-          91d000	Deferred        ai_x64_f
PE	          920000-          a27000	Deferred        dm_x64_f
PE	          a30000-          de1000	Deferred        rl_x64_f
PE	          df0000-          e8c000	Deferred        msvcp140
PE	          e90000-          ea6000	Deferred        vcruntime140
PE	          eb0000-          f06000	Deferred        api-ms-win-crt-heap-l1-1-0
PE	          f10000-          f64000	Deferred        api-ms-win-crt-time-l1-1-0
PE	          f70000-         2a2e000	Deferred        physics_x64_f
PE	         2a30000-         3198000	Deferred        renderer_x64_f
PE	         31a0000-         329c000	Deferred        d3d_x64_f
PE	         32a0000-         3507000	Deferred        d3d11
PE	         3510000-         3969000	Deferred        oleaut32
PE	         3970000-         39ab000	Deferred        app_x64_f
PE	         39b0000-         39cb000	Deferred        loc_x64_f
PE	         39d0000-         3c76000	Deferred        snd_x64_f
PE	         3c80000-         3d9c000	Deferred        videostreamer_x64_f
PE	         3da0000-         3e49000	Deferred        msvfw32
PE	         42b0000-         4304000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	         69b0000-         6b58000	Export          gameoverlayrenderer64
PE	         6b60000-         6bb6000	Deferred        api-ms-win-core-localization-l1-2-1
PE	         7fc0000-         7fc3000	Deferred        xaudio2_8
PE	         b670000-         b767000	Deferred        animationinputlogic_r
PE	        1ed30000-        1ee02000	Deferred        camerasystem_r
PE	        1ee10000-        1ee9d000	Deferred        hud_r
PE	        1f520000-        1f568000	Deferred        particle_simulation_r
PE	        1f680000-        1fb6f000	Deferred        wedrendering_r
PE	        38cf0000-        3913c000	Deferred        d3dcompiler_47
PE	        3a6c0000-        3a74b000	Deferred        xaudio2_7
PE	        3b400000-        3b43f000	Deferred        steam_api64
PE	        48050000-        480e1000	Deferred        xaudio2_9
PE	        48630000-        48684000	Deferred        api-ms-win-core-errorhandling-l1-1-0
PE	        48690000-        486e6000	Deferred        api-ms-win-core-processthreads-l1-1-0
PE	        486f0000-        48744000	Deferred        api-ms-win-core-handle-l1-1-0
PE	        48750000-        487a4000	Deferred        api-ms-win-core-processtopology-obsolete-l1-1-0
PE	        48c70000-        48cc4000	Deferred        api-ms-win-core-delayload-l1-1-0
PE	        61540000-        61596000	Deferred        api-ms-win-crt-locale-l1-1-0
PE	        61780000-        617d7000	Deferred        api-ms-win-core-com-l1-1-0
PE	        61d80000-        61dd4000	Deferred        api-ms-win-core-debug-l1-1-0
PE	        61e40000-        61e94000	Deferred        api-ms-win-core-sysinfo-l1-1-0
PE	        620c0000-        62116000	Deferred        api-ms-win-crt-filesystem-l1-1-0
PE	        62140000-        62225000	Deferred        uxtheme
PE	        62600000-        62722000	Deferred        usp10
PE	        62740000-        627b7000	Deferred        imagehlp
PE	        62c40000-        62c99000	Deferred        api-ms-win-crt-multibyte-l1-1-0
PE	        63140000-        63197000	Deferred        api-ms-win-crt-runtime-l1-1-0
PE	        637c0000-        63975000	Deferred        winmm
PE	        64940000-        649cd000	Deferred        shcore
PE	        64b80000-        64bef000	Deferred        hid
PE	        64d40000-        64d9f000	Deferred        vulkan-1
PE	        65000000-        655da000	Deferred        ole32
PE	        65680000-        656d6000	Deferred        api-ms-win-core-sysinfo-l1-2-1
PE	        65780000-        657e1000	Deferred        version
PE	        65940000-        65994000	Deferred        api-ms-win-core-libraryloader-l1-2-0
PE	        66240000-        66296000	Deferred        api-ms-win-core-threadpool-l1-2-0
PE	        66440000-        664e9000	Deferred        msacm32
PE	        66800000-        6685d000	Deferred        mswsock
PE	        668c0000-        6691c000	Deferred        avrt
PE	        67340000-        67396000	Deferred        api-ms-win-core-delayload-l1-1-1
PE	        68740000-        68796000	Deferred        api-ms-win-core-registry-l1-1-0
PE	        688c0000-        68914000	Deferred        api-ms-win-core-rtlsupport-l1-1-0
PE	        68a40000-        68bbb000	Deferred        shlwapi
PE	        69380000-        693d7000	Deferred        api-ms-win-crt-stdio-l1-1-0
PE	        69840000-        698b5000	Deferred        xinput1_4
PE	        69ac0000-        69b14000	Deferred        api-ms-win-core-profile-l1-1-0
PE	        69b80000-        69bd4000	Deferred        api-ms-win-crt-environment-l1-1-0
PE	        69c80000-        69d40000	Deferred        propsys
PE	        6a4c0000-        6a516000	Deferred        api-ms-win-crt-utility-l1-1-0
PE	        6a700000-        6a902000	Deferred        setupapi
PE	        6ab00000-        6ab56000	Deferred        api-ms-win-core-synch-l1-2-1
PE	        6acc0000-        6ad15000	Deferred        psapi
PE	        6b6c0000-        6b947000	Deferred        comdlg32
PE	        6bec0000-        6bf4f000	Deferred        imm32
PE	        6c300000-        6c356000	Deferred        api-ms-win-core-heap-l1-1-0
PE	        6c580000-        6c5d4000	Deferred        api-ms-win-core-synch-l1-1-0
PE	        6c840000-        6c894000	Deferred        api-ms-win-core-string-obsolete-l1-1-0
PE	        6d580000-        6d5d7000	Deferred        api-ms-win-crt-convert-l1-1-0
PE	        6dd80000-        6ddd7000	Deferred        api-ms-win-crt-string-l1-1-0
PE	        6e340000-        6e396000	Deferred        api-ms-win-core-synch-l1-2-0
PE	        6e480000-        6e5d2000	Deferred        avifil32
PE	        6e6c0000-        6eb22000	Deferred        comctl32
PE	        6f200000-        6f397000	Deferred        dxgi
PE	        6f940000-        6faf0000	Deferred        d3d9
PE	        6fbc0000-        6fe23000	Deferred        rpcrt4
PE	        70140000-        70208000	Deferred        mmdevapi
PE	        704c0000-        70516000	Deferred        api-ms-win-eventing-provider-l1-1-0
PE	        70580000-        705d9000	Deferred        api-ms-win-crt-math-l1-1-0
PE	        71040000-        711c0000	Deferred        kernelbase
PE	        71200000-        71379000	Deferred        mfplat
ELF	        7a800000-        7aa12000	Deferred        opengl32<elf>
  \-PE	        7a850000-        7aa12000	\               opengl32
ELF	        7b400000-        7b867000	Deferred        kernel32<elf>
  \-PE	        7b420000-        7b867000	\               kernel32
ELF	        7bc00000-        7bd61000	Deferred        ntdll<elf>
  \-PE	        7bc20000-        7bd61000	\               ntdll
ELF	        7c000000-        7c005000	Deferred        <wine-loader>
PE	       138000000-       13915d000	Deferred        steamclient64
PE	       13f000000-       13f174000	Deferred        tier0_s64
PE	       13f600000-       13f67a000	Deferred        vstdlib_s64
PE	       140000000-       141316000	Deferred        quantumbreak
PE	       180000000-       180064000	Deferred        bink2w64
ELF	    7fc4dcf78000-    7fc4e0000000	Deferred        libllvm-8.so
ELF	    7fc4e871a000-    7fc4e9601000	Deferred        librenderdoc.so
ELF	    7fc4e9601000-    7fc4e976a000	Deferred        libxml2.so.2
ELF	    7fc4e976a000-    7fc4e97d9000	Deferred        libncursesw.so.6
ELF	    7fc4e9993000-    7fc4e99bf000	Deferred        libmvec.so.1
ELF	    7fc4e99bf000-    7fc4e99d0000	Deferred        libgdbm.so.6
ELF	    7fc4e99d0000-    7fc4e99d9000	Deferred        libogg.so.0
ELF	    7fc4e99d9000-    7fc4e9a14000	Deferred        libvorbis.so.0
ELF	    7fc4e9a14000-    7fc4e9ac0000	Deferred        libvorbisenc.so.2
ELF	    7fc4e9ac0000-    7fc4e9b2f000	Deferred        libflac.so.8
ELF	    7fc4e9b2f000-    7fc4e9ba8000	Deferred        libsndfile.so.1
ELF	    7fc4e9ba8000-    7fc4e9bc6000	Deferred        libice.so.6
ELF	    7fc4e9bc6000-    7fc4e9bd0000	Deferred        libsm.so.6
ELF	    7fc4e9bd0000-    7fc4e9c55000	Deferred        libpulsecommon-12.0.so
ELF	    7fc4e9c55000-    7fc4e9ca9000	Deferred        libpulse.so.0
ELF	    7fc4e9ca9000-    7fc4e9cdf000	Deferred        winepulse<elf>
  \-PE	    7fc4e9cb0000-    7fc4e9cdf000	\               winepulse
ELF	    7fc4f0001000-    7fc4f0009000	Deferred        libxtst.so.6
ELF	    7fc4f0bdd000-    7fc4f1177000	Deferred        libvulkan_radeon.so
ELF	    7fc4f17d5000-    7fc4f17da000	Deferred        libxcb-keysyms.so.1
ELF	    7fc4f17da000-    7fc4f17ed000	Deferred        libdrm.so.2
ELF	    7fc4f17ed000-    7fc4f17f2000	Deferred        libxshmfence.so.1
ELF	    7fc4f17f2000-    7fc4f17fb000	Deferred        libxcb-sync.so.1
ELF	    7fc4f17fb000-    7fc4f1800000	Deferred        libxcb-present.so.0
ELF	    7fc4f1800000-    7fc4f1805000	Deferred        libx11-xcb.so.1
ELF	    7fc4f1805000-    7fc4f1817000	Deferred        libxcb-randr.so.0
ELF	    7fc4f1817000-    7fc4f1832000	Deferred        libelf.so.1
ELF	    7fc4f1832000-    7fc4f183e000	Deferred        libdrm_amdgpu.so.1
ELF	    7fc4f1879000-    7fc4f1904000	Deferred        dbghelp<elf>
  \-PE	    7fc4f1880000-    7fc4f1904000	\               dbghelp
ELF	    7fc4f194a000-    7fc4f1992000	Deferred        netapi32<elf>
  \-PE	    7fc4f1950000-    7fc4f1992000	\               netapi32
ELF	    7fc4f1992000-    7fc4f19e6000	Deferred        secur32<elf>
  \-PE	    7fc4f19a0000-    7fc4f19e6000	\               secur32
ELF	    7fc4f19e6000-    7fc4f1af1000	Deferred        crypt32<elf>
  \-PE	    7fc4f1a00000-    7fc4f1af1000	\               crypt32
ELF	    7fc4f1af1000-    7fc4f1b58000	Deferred        libvulkan.so.1
ELF	    7fc4f1b58000-    7fc4f1b7b000	Deferred        libgpg-error.so.0
ELF	    7fc4f1b7b000-    7fc4f1c98000	Deferred        libgcrypt.so.20
ELF	    7fc4f1c98000-    7fc4f1c9f000	Deferred        libcap.so.2
ELF	    7fc4f1c9f000-    7fc4f1cc7000	Deferred        liblzma.so.5
ELF	    7fc4f1cc7000-    7fc4f1cd1000	Deferred        librt.so.1
ELF	    7fc4f1cd1000-    7fc4f1d95000	Deferred        libsystemd.so.0
ELF	    7fc4f1d95000-    7fc4f1da1000	Deferred        libffi.so.6
ELF	    7fc4f1da1000-    7fc4f1e02000	Deferred        libdbus-1.so.3
ELF	    7fc4f1e02000-    7fc4f1e07000	Deferred        libssp.so.0
ELF	    7fc4f1e07000-    7fc4f1e7b000	Deferred        libgmp.so.10
ELF	    7fc4f1e7b000-    7fc4f1eb4000	Deferred        libhogweed.so.4
ELF	    7fc4f1eb4000-    7fc4f1eec000	Deferred        libnettle.so.6
ELF	    7fc4f1eec000-    7fc4f1f01000	Deferred        libtasn1.so.6
ELF	    7fc4f1f01000-    7fc4f2084000	Deferred        libunistring.so.2
ELF	    7fc4f2084000-    7fc4f21b2000	Deferred        libp11-kit.so.0
ELF	    7fc4f21b2000-    7fc4f21c1000	Deferred        libkrb5support.so.0
ELF	    7fc4f21c1000-    7fc4f21fb000	Deferred        libcrypt.so.1
ELF	    7fc4f21fb000-    7fc4f220e000	Deferred        libavahi-client.so.3
ELF	    7fc4f220e000-    7fc4f221d000	Deferred        libavahi-common.so.3
ELF	    7fc4f221d000-    7fc4f23c3000	Deferred        libgnutls.so.30
ELF	    7fc4f23c5000-    7fc4f23cb000	Deferred        libxcb-dri3.so.0
ELF	    7fc4f23cb000-    7fc4f23d3000	Deferred        libnss_dns.so.2
ELF	    7fc4f23d3000-    7fc4f23f0000	Deferred        kerberos<elf>
  \-PE	    7fc4f23e0000-    7fc4f23f0000	\               kerberos
ELF	    7fc4f23fe000-    7fc4f24d6000	Deferred        libkrb5.so.3
ELF	    7fc4f24d6000-    7fc4f2522000	Deferred        libgssapi_krb5.so.2
ELF	    7fc4f2522000-    7fc4f25a3000	Deferred        libcups.so.2
ELF	    7fc4f25a3000-    7fc4f25ab000	Deferred        libxfixes.so.3
ELF	    7fc4f25ac000-    7fc4f25b2000	Deferred        libcom_err.so.2
ELF	    7fc4f25b2000-    7fc4f25e6000	Deferred        libk5crypto.so.3
ELF	    7fc4f25e6000-    7fc4f25f2000	Deferred        libxcursor.so.1
ELF	    7fc4f25f2000-    7fc4f2605000	Deferred        libxi.so.6
ELF	    7fc4f2605000-    7fc4f2612000	Deferred        libxrandr.so.2
ELF	    7fc4f2612000-    7fc4f261e000	Deferred        libxrender.so.1
ELF	    7fc4f261e000-    7fc4f2647000	Deferred        libxcb.so.1
ELF	    7fc4f2647000-    7fc4f2785000	Deferred        libx11.so.6
ELF	    7fc4f2785000-    7fc4f2849000	Deferred        winex11<elf>
  \-PE	    7fc4f27a0000-    7fc4f2849000	\               winex11
ELF	    7fc4f2849000-    7fc4f2852000	Deferred        libuuid.so.1
ELF	    7fc4f2852000-    7fc4f287f000	Deferred        libexpat.so.1
ELF	    7fc4f287f000-    7fc4f28c4000	Deferred        libfontconfig.so.1
ELF	    7fc4f28c4000-    7fc4f28ed000	Deferred        libgraphite2.so.3
ELF	    7fc4f28ed000-    7fc4f290a000	Deferred        libz.so.1
ELF	    7fc4f290a000-    7fc4f2942000	Deferred        libpng16.so.16
ELF	    7fc4f2942000-    7fc4f2955000	Deferred        libbz2.so.1.0
ELF	    7fc4f2955000-    7fc4f299b000	Deferred        libpcre.so.1
ELF	    7fc4f299b000-    7fc4f2abf000	Deferred        libglib-2.0.so.0
ELF	    7fc4f2abf000-    7fc4f2bbb000	Deferred        libharfbuzz.so.0
ELF	    7fc4f2bbd000-    7fc4f2bc2000	Deferred        libxcomposite.so.1
ELF	    7fc4f2bc2000-    7fc4f2bc9000	Deferred        libxxf86vm.so.1
ELF	    7fc4f2bc9000-    7fc4f2bce000	Deferred        libxinerama.so.1
ELF	    7fc4f2bce000-    7fc4f2bd6000	Deferred        libxdmcp.so.6
ELF	    7fc4f2bd6000-    7fc4f2bdb000	Deferred        libxau.so.6
ELF	    7fc4f2bdb000-    7fc4f2bef000	Deferred        libxext.so.6
ELF	    7fc4f2bf6000-    7fc4f2cb3000	Deferred        libfreetype.so.6
ELF	    7fc4f2cb3000-    7fc4f2cd9000	Deferred        bcrypt<elf>
  \-PE	    7fc4f2cc0000-    7fc4f2cd9000	\               bcrypt
ELF	    7fc4f2cd9000-    7fc4f2d2b000	Deferred        winevulkan<elf>
  \-PE	    7fc4f2cf0000-    7fc4f2d2b000	\               winevulkan
ELF	    7fc4f2d2b000-    7fc4f2ec1000	Deferred        wined3d<elf>
  \-PE	    7fc4f2d50000-    7fc4f2ec1000	\               wined3d
ELF	    7fc4f2ec1000-    7fc4f2eda000	Deferred        libresolv.so.2
ELF	    7fc4f2eda000-    7fc4f301a000	Deferred        ucrtbase<elf>
  \-PE	    7fc4f2f10000-    7fc4f301a000	\               ucrtbase
ELF	    7fc4f301a000-    7fc4f305d000	Deferred        ws2_32<elf>
  \-PE	    7fc4f3020000-    7fc4f305d000	\               ws2_32
ELF	    7fc4f305d000-    7fc4f30c0000	Deferred        winspool<elf>
  \-PE	    7fc4f3070000-    7fc4f30c0000	\               winspool
ELF	    7fc4f30c0000-    7fc4f3b10000	Deferred        shell32<elf>
  \-PE	    7fc4f30e0000-    7fc4f3b10000	\               shell32
ELF	    7fc4f3b10000-    7fc4f3c04000	Deferred        msvcrt<elf>
  \-PE	    7fc4f3b30000-    7fc4f3c04000	\               msvcrt
ELF	    7fc4f3c04000-    7fc4f3c9b000	Deferred        advapi32<elf>
  \-PE	    7fc4f3c20000-    7fc4f3c9b000	\               advapi32
ELF	    7fc4f3c9b000-    7fc4f3e4c000	Deferred        gdi32<elf>
  \-PE	    7fc4f3cb0000-    7fc4f3e4c000	\               gdi32
ELF	    7fc4f3f4c000-    7fc4f41dc000	Deferred        user32<elf>
  \-PE	    7fc4f3f70000-    7fc4f41dc000	\               user32
ELF	    7fc4f567f000-    7fc4f5694000	Deferred        libnss_files.so.2
ELF	    7fc4f569c000-    7fc4f56cf000	Deferred        iphlpapi<elf>
  \-PE	    7fc4f56b0000-    7fc4f56cf000	\               iphlpapi
ELF	    7fc4f58cf000-    7fc4f58e9000	Deferred        libgcc_s.so.1
ELF	    7fc4f58e9000-    7fc4f5a2e000	Deferred        libm.so.6
ELF	    7fc4f5a30000-    7fc4f5a35000	Deferred        libdl.so.2
ELF	    7fc4f5a35000-    7fc4f5bf5000	Deferred        libc.so.6
ELF	    7fc4f5bf5000-    7fc4f5c16000	Deferred        libpthread.so.0
ELF	    7fc4f5dbf000-    7fc4f5de9000	Deferred        ld-linux-x86-64.so.2
Threads:
System information:
    Wine build: wine-4.12.1
    Platform: x86_64
    Version: Windows 7
    Host system: Linux
    Host version: 5.2.1

**Comment by NTMan** [comment] 2019-07-20 14:39
> I don't know how to play and the previously mentioned control
> problems.

Maybe because I used the gamepad for playing. Thus, for playing on keyboard you should change settings.

> Behind me it was pitch dark and in front of me there were bad guys with guns that killed me right on the spot.

You should kill all the bad guys on this floor.

> I manage to capture some renderdocs with the steam version.

How you do this? When I trying added `ENABLE_VULKAN_RENDERDOC_CAPTURE=1` the game stop launching.

**Comment by SR-dude** [comment] 2019-07-20 14:47
>You should kill all the bad guys on this floor.

I couldn't kill the guys, That's what I'm saying.
I can't aim because of the mouse. It shouldn't
matter anyway there were plenty of renderdocs
to capture earlier.

>How you do this? 

I don't know. Your environment variable looks the same as mine.
Is your renderdoc ICD in place? What version of renderdoc are
 you using?

I just checked and to anyone who is interested amazon still has the
 game for sale for $10. But it won't be for long.

Time left to upload 53 mins.

**Comment by daniel-schuermann** [comment] 2019-07-20 14:52
Are the crashes also happening with the steam version?
And could you capture the flickering (so that it is visible in the capture)?

**Comment by NTMan** [comment] 2019-07-20 14:53
> Is your renderdoc ICD in place? What version of renderdoc are
you using?

If you add `ENABLE_VULKAN_RENDERDOC_CAPTURE=1 %command%` to launch option would be used renderdoc integrated in steam. It works like magic if no other problem occurred.

**Comment by SR-dude** [comment] 2019-07-20 14:57
> Are the crashes also happening with the steam version?
> And could you capture the flickering (so that it is visible in the capture)?

I only have the steam version.
And for your second question. I just simply press f12.

**Comment by SR-dude** [comment] 2019-07-20 15:00
> If you add `ENABLE_VULKAN_RENDERDOC_CAPTURE=1 %command%` to launch option would be used renderdoc integrated in steam. It works like magic if no other problem occurred.

I'm not using %command$ since I'm not using steam play.
I start the windows version of Steam like this:

env ENABLE_VULKAN_RENDERDOC_CAPTURE=1 wine Steam.exe

**Comment by daniel-schuermann** [comment] 2019-07-20 15:07
> > Are the crashes also happening with the steam version?

> I only have the steam version.

Sorry, I meant: Do the crashes also happen with the Linux version + Proton?

**Comment by SR-dude** [comment] 2019-07-20 15:11
> Sorry, I meant: Do the crashes also happen with the Linux version + Proton?

I have not yet attempted to use SteamPlay. But I'll try different wine versions first.


30 more minutes on a capture.

**Comment by daniel-schuermann** [comment] 2019-07-20 15:14
> And for your second question. I just simply press f12.

Please check the captures before uploading them that they contain the actual problem. Otherwise, we won't be able to get anything useful from them.

**Comment by SR-dude** [comment] 2019-07-20 15:47
Frame 1
https://drive.google.com/open?id=1LkyDlZ3mHeEomdASSPuYXEhK0zhYyqjE

Frame 2
https://drive.google.com/open?id=138f_x-0k3jEvkxMsU3rxIrn61CgR0x2V

**Comment by daniel-schuermann** [comment] 2019-07-20 19:57
Thx, we can reproduce the issue with the captures you provided.

**Comment by SR-dude** [comment] 2019-07-20 20:25
Do you need any further captures?  Because, I made into the room that the OP posted the video about.

**Comment by daniel-schuermann** [comment] 2019-08-05 16:58
Seems, this got accidentally fixed by @pendingchaos who found it just being awesome (70bb3c0becd810e3e82cad11f93e33970716eb70)

**Comment by SR-dude** [comment] 2019-08-05 17:49
Confirmed. It is fixed.

**Comment by NTMan** [comment] 2019-08-05 19:07
I also confirm that the artifacts is fixed, but FPS still below acceptable even on medium settings when "Time Vision" is used.

![Screenshot from 2019-08-05 23-58-48](https://user-images.githubusercontent.com/200750/62488496-d9b9d200-b7dd-11e9-8970-53ca6a5c04ae.png)

**Comment by SR-dude** [comment] 2019-08-06 11:37
I'm going to delete my captures, unless someone wants them.
I'll give you a day to grab them.

**Comment by SR-dude** [comment] 2019-08-08 22:58
Needs closing.

**Comment by daniel-schuermann** [comment] 2019-08-09 10:41
Thanks for the help! W.r.t. the slow performance, I'd be glad if you open a new issue for that.

**Closed as completed by daniel-schuermann** 2019-08-09 10:41 UTC
