### ISSUE TITLE
A Problem with The Sinking City

### ISSUE THREAD

**Issue by SR-dude** [daniel-schuermann/mesa#64] opened 2019-07-07 15:24 UTC
There is a problem with Epic's exclusive title: The Sinking City.  
See for yourself.
![Screenshot from 2019-07-07 15-03-22](https://user-images.githubusercontent.com/935631/60770466-198b7d80-a0a9-11e9-9a21-b5225b033ca2.png)

Another one.
![Screenshot from 2019-07-07 15-02-26](https://user-images.githubusercontent.com/935631/60770502-450e6800-a0a9-11e9-9454-f0c0794651be.png)

That doesn't happen with mesa master. The glowing eyes with the black bars coming out of them are not constant. They flash. I managed to get a screenshot where the eyes looked
normal and no black bars.

**Comment by daniel-schuermann** [comment] 2019-07-08 14:23
Thank you for reporting the issue. Would it be possible for you to take a renderdoc capture from this scene? Unfortunately, I don't own this game.

**Comment by SR-dude** [comment] 2019-07-08 14:30
I'm trying to work on that. I currently don't  have renderdoc.  Is the optional python dependency  PySide2 really necessary for renderdoc? I installed it with pip but renderdoc's cmake scripts can't seem to find it.

**Comment by daniel-schuermann** [comment] 2019-07-08 14:41
renderdoc is quite hard to build, so I'd try to use the distro-provided or pre-build binaries.

**Comment by SR-dude** [comment] 2019-07-09 12:48
The problem isn't present on the master branch. I previously reported while on the backend branch.
I'll try the backend branch again.

+
I have renderdoc but I haven't had much success at getting a capture. It is not  a drm-free game and I already need to run Epic through Lutris. I even tried to install the Windows version of Renderdoc inside of Epic's Lutris generated prefix. The game just simply broke out of the prefix "jail" and claimed the Epic game launcher wasn't running. I'll ask for help from the community.

**Comment by daniel-schuermann** [comment] 2019-07-10 06:47
ping. Hey, could you confirm that this issue is resolved on the backend branch as well? Or is it still an issue. Thx!

**Comment by SR-dude** [comment] 2019-07-10 11:43
I was playing this game all day yesterday without issue on the master branch.
Yes, it is still a problem with the backend branch.
![Screenshot from 2019-07-10 11-30-12](https://user-images.githubusercontent.com/935631/60966338-fe598180-a2e5-11e9-8c95-ffcba9494125.png)
![Screenshot from 2019-07-10 11-36-20](https://user-images.githubusercontent.com/935631/60966347-074a5300-a2e6-11e9-9b1b-aa38cdd9785e.png)

With the second screehshot one the  gentleman's back is turned from the camera but still the eyes glow.

**Comment by daniel-schuermann** [comment] 2019-07-11 05:58
Hi SR-dude,
would you like to test https://github.com/daniel-schuermann/mesa/tree/backend_issue_64 to confirm that the issue is not present on this branch? It is the same branch with one commit removed where we think might be the error. Thx!

**Comment by SR-dude** [comment] 2019-07-11 16:08
I tried 'backend_issue_64' and the issue still occurs. Sorry.

**Comment by daniel-schuermann** [comment] 2019-07-11 16:35
hm, okay. we only had a guess which commit it might be, but was apparently wrong. So, we updated the branch https://github.com/daniel-schuermann/mesa/tree/backend_issue_64 again where basically all changes from the backend branch are reverted, so that it's only a rebased master branch.
I'd appreciate if you could retest again, and if it then works and you find the time, would you be able bisect this branch to find the commit which is responsible for this regression? Thx alot!

**Comment by SR-dude** [comment] 2019-07-11 17:26
Alright, no glowing eyes with backend_issue_64 branch as of now. Tell me again which branch you want me to bisect and which range of commits?

**Comment by daniel-schuermann** [comment] 2019-07-11 17:33
this branch you just tested :)
it has a bunch of reverts as last commits. so, knowing which revert exactly made it work again would be gold! thx

**Comment by SR-dude** [comment] 2019-07-11 18:06
The rebase ruled out a dirct bisect. Git complained about refs
not being direct ancestors of of newer commits But there were
only a hand full of commits to test. So, I did it manually.
These are the commits in order as git reports them. The first
good commit with no glowing eyes was 532679...

commit 9bc391c7857ca1255b40155d27234fe9877a3d84 not glowing
commit a0e5ca745361718242e82ae019f86610cfed2ba2 didn't test
commit 4ea0889f56940894161d7d3285dbe13ec0cd04e6 didn't test
commit 17eb854870b87f0602a7be2061f3a448c5af62db didn't test
commit 515538edf581fec1fe840702e269509817182a22 not glowing
commit 53267942ec015f76ba943ec5c4924eb6759c0708 not glowing
commit 3b7f3b51370de9dc168828882d9fe44a18efcc75 glowing eyes
commit 69fe03aed4c9dc11b92738068e4fefde25ddcfff glowing eyes
commit bb40825e9a728e7e8708f082eae0c2d9565ecc7c glowing eyes
commit 21326c9958cc5bb5b11db57c4dfb0cd86de56fec glowing eyes
commit 8c6ebf61d7ab4454b06e195664de631948c3ec1b glowing eyes

**Comment by daniel-schuermann** [comment] 2019-07-12 16:22
SR-dude, thx for this investigation. I rewrote the part which happened to be the only case which was affected by the commit which apparently broke Sinking City (although I still don't really understand what could have gone wrong there). Would you retest the normal 'backend' branch? Thx

**Comment by SR-dude** [comment] 2019-07-12 17:03
On the backend branch the eyes glow.
+
Let's talk about renderdoc. As far as I know there are two ways to work this suite.
First, you fill out the fields: Executable Path, Working Directory, Command-line 
Arguments, and Finally Environment Variables. Second, you attach to an already 
running process. That only works if you can attach before your vulkan instance is
created.

One big problem I have is isolating the main game binary from its DRM. I tried the
first approach only to be told be the game that Epic needed to be run and logged in.
I was but the game couln't see it.  I'm not sure what to do here.

**Comment by daniel-schuermann** [comment] 2019-07-12 17:07
Did you try to just set
- ENABLE_VULKAN_RENDERDOC_CAPTURE=1
and start the launcher from command line with this ENV var? For steam, this works with most games. If the drm is too strong, then I doubt we get it hooked :(

**Comment by daniel-schuermann** [comment] 2019-07-12 19:11
Ok, I force-pushed to the backend_issue_64 branch, so that it is just the updated backend branch with the commit you bisected, reverted. Do you mind testing the backend_issue_64 branch again? I admit, I'm quite confused.
(if you pull, use -f because of the force-push)

**Comment by SR-dude** [comment] 2019-07-12 19:56
Thank for the tip! Here it is.

https://drive.google.com/open?id=18aBQdgYYp_oFF5ds6JVm80Efg9RjOD9b

**Comment by pendingchaos** [comment] 2019-07-12 21:02
Thanks, should be fixed with 0e2241145ac4d74bbf1eff3fc92e48c1d12ffc16

**Closed as completed by pendingchaos** 2019-07-12 21:02 UTC

**Comment by SR-dude** [comment] 2019-07-20 13:35
I'm about to permanently delete the renderdoc, unless anyone wants it. I'll give you 12 hours to grab it.
