### ISSUE TITLE
SUPERHOT (322500) - Crash on startup - Needs confirmation

### ISSUE THREAD

**Issue by kode54** [daniel-schuermann/mesa#172] opened 2020-01-07 03:14 UTC
**Describe the bug**
SUPERHOT crashes on startup when using the latest snapshot of mesa-aco-git. It starts up successfully with `RADVPERFTEST=llvm`, but still has random glitches in the launcher dialog every time it redraws.

It also runs successfully, with the same launcher glitches, with `mesa-tkg-git` with `RADVPERFTEST=aco` enabled.

**Screenshots**
No screen shots of the crash, since they don't spring a crash dialog. I can post a screen shot of the graphical glitches from the launcher, if that helps. The game runs properly with `mesa-aco-git` if ACO is disabled, or with `mesa-tkg-git` with ACO enabled.

**RenderDoc capture:**
Probably not useful, as the ACO package is causing it to crash on startup, so there's really nothing to capture rendering of.

**System information:**
 - GPU:  Radeon RX480
 - ACO version: 20.0.0_devel.20191204.3409c06e26d-1

- TkG version, just for comparison: 20.0.0_devel.118907.680d8069509-1

**Additional context**
I do not own this game on Steam, so I need someone who has it available to confirm this issue for me. I am using the Epic Game Store version via Lutris, using lutris-4.20 runner. Maybe this bug report isn't so useful after all?

**Comment by daniel-schuermann** [comment] 2020-01-30 08:47
Sure it's useful! Does this issue still persist? If so, would you be able to do one or more of the following?
- create a debug build of mesa, run the game with aco and when it crashes paste /.steam/error.log
- take a renderdoc capture using LLVM directly after ACO would have crashed and confirm that opening it with ACO makes renderdoc crash as well

**Comment by kode54** [comment] 2020-01-31 05:39
It no longer crashes as of `20.0.0_devel.20200127.5db39a5a28e-1`, but it has an issue that I haven't been able to pin to either Mesa-git, Mesa-ACO-git, stable Mesa, or the Wine version in use. Basically, the launcher turns into uninitialized VRAM garbage shortly after launch, and must be bypassed by clicking at it blindly.

**Comment by pendingchaos** [comment] 2020-02-20 19:43
Closing since any ACO-related issues are apparently resolved

Please open an issue on https://gitlab.freedesktop.org/mesa/mesa/issues if the launcher issue is still present and turns out to be caused by Mesa

**Closed as completed by pendingchaos** 2020-02-20 19:43 UTC
Labels: Polaris, Crash
