### ISSUE TITLE
Temtem (745920) missing icons

### ISSUE THREAD

**Issue by HanPrower** [daniel-schuermann/mesa#178] opened 2020-01-28 11:41 UTC
**Describe the bug**
Temtem renders certain icons during battles such as whose turn it is, buffs/debuffs, etc. Whilst ACO is enabled these icons are absent.

**Screenshots**
With RADV_PERFEST=aco:
![temtem_with_aco](https://user-images.githubusercontent.com/1781312/73260004-ea616880-41c0-11ea-81b5-8a0d19ef8790.jpg)

Without RADV_PERFEST=aco (note the blue <> and white circle around certain creatures):
![temtem_without_aco](https://user-images.githubusercontent.com/1781312/73260014-edf4ef80-41c0-11ea-9e4b-11ca37d34232.jpg)

**RenderDoc capture:**
https://www.mediafire.com/view/yf37u99ooou8o4t/temtem_2020.01.28_11.17_frame37339.rdc/file

**System information:**
 - GPU: Radeon RX 5700 XT
 - ACO version: mesa-git  1:20.0.0_devel.119683.fe5267d3223-1 (from 3rd party Arch repo mesa-git)

**Additional context**
Another user with an RX 580 states that they didn't have icons either, and using RADV_PERFEST=llvm fixed it for them: https://github.com/ValveSoftware/Proton/issues/3441#issuecomment-578411119

**Comment by pendingchaos** [comment] 2020-02-05 15:24
I've created a work-in-progress MR which seems to fix this issue: https://gitlab.freedesktop.org/mesa/mesa/merge_requests/3716

**Comment by nicodemus144** [comment] 2020-03-31 20:28
just chiming in. i'm also having this issue. currently on mesa 20.0.2 and the issue remains. unsure on the timetable for the fix.

thanks for all you do!

**Comment by pendingchaos** [comment] 2020-03-31 20:44
Yeah, the issue isn't fixed yet

I have a patch to fix it, I need to remind some people about it though so that it can be merged

**Comment by nicodemus144** [comment] 2020-03-31 20:51
thanks for letting me know! for whatever reason, RADV_PERFEST=llvm doesn't fix it for me, so hoping for that merge soon!

**Comment by nicodemus144** [comment] 2020-04-10 15:28
as of yesterday, this seems fixed for me.

i'm on kernel 5.6.3 and mesa 20.0.4

thank you!

**Comment by pendingchaos** [comment] 2020-04-10 16:49
@nicodemus144 : That is strange (both it working correctly and RADV_PERFTEST=llvm not fixing it)

I suspect you have a slightly different issue (maybe same appearance but different cause), since RADV_PERFTEST=llvm should fix this and it should still be broken in Mesa 20.0.4

It's also possible some version of LLVM had a similar bug and RADV_PERFTEST=llvm started fixing it after a LLVM update

**Comment by nicodemus144** [comment] 2020-04-10 17:08
interesting. well, it's not LLVM since i'm not using any launch options. i'm on ACO by default.

ok, well, just letting you know!

**Comment by pendingchaos** [comment] 2020-05-07 12:06
This issue should be fixed in the latest mesa-git, so I'll close this issue

**Closed as completed by pendingchaos** 2020-05-07 12:06 UTC
Labels: Corruption
