### ISSUE TITLE
Shadows issue with ACO for AC : Origins

### ISSUE THREAD

**Issue by Bulbyzarr** [daniel-schuermann/mesa#105] opened 2019-08-10 09:31 UTC
**Describe the bug**
Shadows issues when the game is launched with Mesa-ACO. No issue when the game is launched with "RADV_PREFTEST=llvm"

**Screenshots**
![AC Origins + ACO](https://user-images.githubusercontent.com/3606036/62820241-ad95ac80-bb61-11e9-8dd7-f727ab817b6e.png)
![AC Origins + LLVM](https://user-images.githubusercontent.com/3606036/62820243-bbe3c880-bb61-11e9-80da-29b6469f9356.png)

**RenderDoc capture:**
[https://drive.google.com/open?id=1hbHr54QoNBBSHPg4Q5y_bUG_murlPf3K](https://drive.google.com/open?id=1hbHr54QoNBBSHPg4Q5y_bUG_murlPf3K)

**System information:**
 - GPU: AMD Rx580 8Gb
 - ACO version: [34dd1dd](https://github.com/daniel-schuermann/mesa/commit/34dd1ddde6f6c19249c32d9c7024f3dc919c18d1)

**Comment by Bulbyzarr** [comment] 2019-08-15 06:01
This report is not interesting ?

**Comment by daniel-schuermann** [comment] 2019-08-15 07:54
This issue is already interesting for the naming confusion by itself. You could call it ACO² ;)
Jokes aside, we are only 2 people and the ordering in which we handle things also depends on what we're currently working on and more things (e.g. I always have to swap cards between vega and polaris).

**Comment by daniel-schuermann** [comment] 2019-08-15 09:03
hm, I'm a bit confused because of the following:
The commit you mention (34dd1ddde6f6c19249c32d9c7024f3dc919c18d1) causes a hang for me if I try to open the capture with LLVM (my LLVM version is probably different, though). Opening it with ACO gives me a completely black picture with only the HUD visible. The same happens when I open it with current master with LLVM. To open it with ACO on current master, https://gitlab.freedesktop.org/mesa/mesa/merge_requests/1664 is required, but then again the picture is black. Did you test to open the capture (with qrenderdoc)?

**Comment by Bulbyzarr** [comment] 2019-08-15 12:20
Hum... Renderdoc crashes when i open the capture with ACO and hangs my PC when i open the capture with LLVM.

I'll do a new capture tomorrow after to download the game.

**Comment by DistantThunder** [comment] 2019-08-15 17:00
I also observe this problem. Compiled ACO on the 13th Aug. 2019, can't find the revision or the commit though...

**Comment by Bulbyzarr** [comment] 2019-08-15 20:26
@daniel-schuermann, i did a new capture but unfortunatly, it still hang my PC when i open it with renderdoc (LLVM & ACO). This capture was made with LLVM 8.0.1 + ACO-git commit [597ea28](https://github.com/daniel-schuermann/mesa/commit/597ea28554129ce49f353f07dcdb105ae8215c35)

**Comment by daniel-schuermann** [comment] 2019-08-15 20:42
Would you try with a0a7fa7531b75759c74011ca5bde8e49c1f8e151 ? If you're using a repository, it might take a few hours until it lands, though.

**Comment by Odelpasso** [comment] 2019-08-15 21:30
I'm on Gentoo, it's easy to have latest git for ACO ;-).
Unfortunatly, renderdoc still crashes during the opening of the capture. When i check on the output console, the crash comes after this line : 
`Warning - Capture may be missing reference to VkEvent resource (12706)`

**Comment by Bulbyzarr** [comment] 2019-08-15 22:49
Good news, with the latest commit [a0a7fa7](https://github.com/daniel-schuermann/mesa/commit/a0a7fa7531b75759c74011ca5bde8e49c1f8e151), the capture is open without issue.

You can download the new capture [here](https://drive.google.com/open?id=1DcMD2MVJW06kKWWOlnjTSsbA3Y2k0g_H)

![Capture du 2019-08-16 00-48-16](https://user-images.githubusercontent.com/3606036/63131901-991d3e00-bfbf-11e9-87bf-416c7138154b.png)

You can see the graphical issue between the 3rd and 4th statues on the right.

**Comment by mpawlowski7** [comment] 2019-08-16 06:14
This issue also occurs in AC: Odyssey. Here is in shadows casted on trees on the left:
![Zrzut ekranu z 2019-08-16 07-33-13](https://user-images.githubusercontent.com/11025071/63146669-0b137880-bffc-11e9-9725-04c84d6b0803.png)

and also on waves:
![Zrzut ekranu z 2019-08-16 07-36-19](https://user-images.githubusercontent.com/11025071/63147244-cee11780-bffd-11e9-91a5-dd00a029fc70.png)

and RenderDoc captures corresponding to those shots:
https://drive.google.com/file/d/1v5Ig0SW35XwgPIZVDxlxeWa70W1YqYej/view?usp=sharing
https://drive.google.com/file/d/1NC1OjfMVLNpcfTTd7xFIzd1GTPmGVnfF/view?usp=sharing

I'm using Ubuntu 19.04 with aco a0a7fa7 my GPU is AMD RX480.

**Comment by daniel-schuermann** [comment] 2019-08-16 15:47
Can you please confirm if this issue is fixed with 650031018b4a596431e383ab619b7398bb4de74d ?

**Comment by Bulbyzarr** [comment] 2019-08-16 16:29
Works for me, thanks Daniel :-)

Other question, the performance in-game are the same than with plain LLVM when i run 
![Origins benchmark](https://user-images.githubusercontent.com/3606036/63182792-a71c9e80-c053-11e9-8197-991cc7a1ca09.png).

There would be a possibility to improve performance or not ?
I tried tomorrow to run the benchmark on Win10 too to compare with mesa-ACO.

**Comment by daniel-schuermann** [comment] 2019-08-16 16:34
> Works for me, thanks Daniel :-)

You're welcome :)
> There would be a possibility to improve performance or not ?

Depends on what is the limiting factor here, but with equal performance, it will probably not be in focus to be optimized for the near future. Maybe it will benefit from other/general optimizations.
> I tried tomorrow to run the benchmark on Win10 too to compare with mesa-ACO.

Make sure to run both sides a couple of times to get a consistent impression and I'd be glad to see the results in the benchmark issue.

Thx

**Closed as completed by daniel-schuermann** 2019-08-16 16:34 UTC

**Comment by aufkrawall** [comment] 2019-08-16 16:37
> There would be a possibility to improve performance or not ?

The game is very demanding also on Windows.  Though it makes sense to reduce cloud quality by one or two levels, as it seems to waste a lot of performance for almost no visible effect.
Setting AA to lower levels makes it use upscaling, but of course this only helps if the game isn't CPU bound (which might be the case with Ryzen 1000 CPUs).

Frametimes might look more even when using `dxgi.maxFrameLatency = 1`, but I'd use DXVK's own graph for it and not the weird one of the game's benchmark.

Edit: Whoops, I confused that you play Origins and not Odyssey. For Origins, only my remark regarding that DXVK option is valid.

**Comment by mpawlowski7** [comment] 2019-08-17 19:11
I can confirm that it also worked for AC Odyssey. Thank you :)
