### ISSUE TITLE
Battlefront 2 (2017) graphical corruption

### ISSUE THREAD

**Issue by ptkato** [daniel-schuermann/mesa#147] opened 2019-10-05 17:39 UTC
The game only crashes on specific maps, it seems to happen with 100% consistency on Capital Supremacy's Felucia, Kashyyyk and Genosis, the furtherest I could get into it was 5~10 seconds of the initial cinematic, if I join and it's in the middle of the match, it crashes when I pick a class and go to the pick a spawn screen. However, it doesn't crash in the ship phase, I can join the game then just fine, and it plays ok until it goes back to the ground phase, which is followed by a crash.

One thing about those maps is that I can play them if they're in Galactic Assault or Arcade.

### Software information
Battlefront 2, Origin version, all the video options set to low.

### System information
- GPU: RX 550
- Driver: Mesa ACO 19.3.0, 6c3bad5214b
- Wine version: Staging 4.14
- DXVK version: 1.4.1

This issue was originally reported at [DXVK's issue tracker](https://github.com/doitsujin/dxvk/issues/1214).

**Comment by daniel-schuermann** [comment] 2019-10-06 21:10
Hi, thx for the report. Does this issue also happen with RADV_PERFTEST=llvm? Would you be able to create a debug build of aco and provide the stderr output?

**Comment by ptkato** [comment] 2019-10-06 23:17
It doesn't happen on LLVM, however the game has massive hangs without ACO, which makes it unplayable.

I'm using Lutris, which gobbles up the stderr, so the output might have some unrelated things: https://paste.ubuntu.com/p/WmMMTvKjZ7/

**Comment by daniel-schuermann** [comment] 2019-10-06 23:59
Thx! We have an idea about where the bug is now, but we'll probably need a renderdoc capture to be able to replay it. Would you be able to start the game using llvm and try to capture a moment which makes aco fail? (You can check on being successful by opening the capture with aco, renderdoc should crash as well in this case)

**Comment by ptkato** [comment] 2019-10-07 00:54
~~What do you mean by "start the game using llvm and try to capture a moment which makes aco fail"?~~

~~Is that just use LLVM instead and capture the moment where ACO would crash, if it were being used instead?~~

Edit: nevermind that, now I understand what you mean.

**Comment by ptkato** [comment] 2019-10-07 20:53
I don't think I'd be able to do a renderdoc capture, I couldn't manage to launch Origin through a 64 bit wine executable and 32 bit wine just crashes, since it seems that renderdoc doesn't support 32 bit under Linux.

**Comment by daniel-schuermann** [comment] 2019-10-08 11:38
@ptkato Oh yeah, that's a bit unfortunate. Maybe try https://gitlab.freedesktop.org/mesa/vkpipeline-db ? This let's you dump the shaders while playing and we should be able to replay them locally. I'd expect this to be enough as it isn't a rendering bug but just a shader not compiling.
Maybe send me a link with the uploaded pipelines instead of posting them here (not all publishers like seeing their shaders dumped somewhere).

**Comment by pendingchaos** [comment] 2019-10-08 11:56
I think you'll have to use LLVM in the map that ACO would crash with when capturing the pipelines, by the way.

**Comment by ptkato** [comment] 2019-10-09 01:06
@daniel-schuermann where can I send you the link?

I sent it to you on freenode, if that's ok.

**Comment by daniel-schuermann** [comment] 2019-10-09 07:07
Thx, the broken shader is indeed part of the collection. We'll keep you posted.

**Comment by daniel-schuermann** [comment] 2019-10-31 10:11
Can you confirm if the issue is fixed with the latest update?

**Comment by ptkato** [comment] 2019-10-31 20:21
Alas, I can't. The game is crashing to desktop the second I open it, in the first loading screen. However I don't think it's related to ACO, since it happens on LLVM too.

**Comment by gort818** [comment] 2019-11-02 05:03
@ptkato Yeah I tried to test it as well but cannot even load the game atm.

**Comment by gort818** [comment] 2019-11-05 01:54
@ptkato I got it running with https://github.com/Tk-Glitch/PKGBUILDS/releases/tag/4.19.r0.g1f775840

I will be testing if there are any crashes.

**Comment by gort818** [comment] 2019-11-05 15:13
Ok so there is no way to pick exactly what maps on Capital Supremacy.. unfortunately didn't get any of those maps.. but so far running smooth about 70-80 fps on ultra with ryzen 3700x and vega56.

There are some strange graphics glitches on certain maps I will make another report.

**Comment by daniel-schuermann** [comment] 2019-12-04 12:07
@gort818 Would you retest if the corruption is still visible? We had some bug fixes which affected some of the SW:BF2 shaders, which means that there is the possibility that they have been fixed. If these are still visible, would you be able to grab a renderdoc capture of the scene?
Thx in advance

**Comment by pendingchaos** [comment] 2019-12-04 12:09
The bug fix hasn't been upstreamed yet btw: https://gitlab.freedesktop.org/mesa/mesa/merge_requests/2945

It's in this github repo though

EDIT: it's now upstreamed

**Comment by gort818** [comment] 2019-12-04 15:02
@daniel-schuermann yes definitely , it only happens on certain maps and the game doesn't let you chose maps. I will try this week, thanks!

**Comment by gort818** [comment] 2019-12-11 16:31
@daniel-schuermann So I played for a few hours on many different maps, everything seems to be working fine.

**Comment by pendingchaos** [comment] 2019-12-18 17:59
Thanks, I'll be closing this issue

**Closed as completed by pendingchaos** 2019-12-18 17:59 UTC
Labels: Vega, Polaris, Corruption
