### ISSUE TITLE
Overwatch issues with fog

### ISSUE THREAD

**Issue by lordkitsuna** [daniel-schuermann/mesa#38] opened 2019-07-03 21:34 UTC
Using ACO Overwatch seems to have an issue with fog, the entire map is covered in a thick fog that also flickers. Here is a renderdoc (compressed with lrzip) as well as a screenshot of the fog. Reproduction is easy, just enter any game match and the fog will be present. Please let me know if i can provide any further information that would be helpful. https://drive.google.com/open?id=1ybrORUCCCXZRnzT-QQG8-pbPihXZwqwN 
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/3444267/60626303-38cf9580-9d9f-11e9-8be3-74930f7cddb1.png">

System specs:
OS: Antergos Linux x86_64 
Kernel: 5.1.4-12-tkg-pds 
DE: KDE 
WM: KWin 
CPU: Intel i7-5820K (12) @ 4.600GHz 
GPU: AMD ATI Radeon RX Vega 56 
Memory: 48120MiB 
Game was run using DXVK: 1.2.3

**Comment by ghost** [comment] 2019-07-03 23:19
I'd like to test Overwatch but I'm afraid of getting banned.

**Comment by daniel-schuermann** [comment] 2019-07-04 06:51
Thanks for reporting! For some reason, I get a segfault trying to decompress the capture. Could you re-uplad it uncompressed?

**Comment by daniel-schuermann** [comment] 2019-07-04 09:12
nvm, I got it decompressed with 1 thread. seems to be a faulty lrzip version in Ubuntu.

**Comment by daniel-schuermann** [comment] 2019-07-04 10:21
I cannot reproduce the error with ACO. I get these pictures from your renderdoc capture:
https://imgur.com/a/pCPXtwn
which seems to me like LLVM is broken, not ACO (using 9.0-git).
How exactly should the picture look like?

**Comment by lordkitsuna** [comment] 2019-07-04 11:15
Thanks for getting to this so quickly! here is a screenshot and new renderdoc showing what it should look like using the RADV_PERFTEST=llvm flag
https://drive.google.com/open?id=13-r1OyHNnor658F2Y-tsDq0pYw5OgUmh
<img width="1920" alt="Screenshot_20190704_035510" src="https://user-images.githubusercontent.com/3444267/60662798-3a867100-9e12-11e9-82cb-66a54d88b48f.png">

**Comment by daniel-schuermann** [comment] 2019-07-04 13:03
By the looks of things, it seems the broken texture is not rendered in this frame. Probably, the texture gets rendered when the level is loaded which is extremely hard to track down (even worse with the anti-cheat probably won't allow it neither).
It seems, for the moment, we are just stuck with it. If you care and have time, you could try to find a similar issue in a different scene/level or maybe a mismatch in the main menu hoping they originate from the same bug.

**Comment by thunder1410** [comment] 2019-07-07 12:01
This issue is for me also present in the shooting range (training).
Sytem information: https://gist.github.com/thunder1410/76897c9bd211c74b30968baa4037ce96
Shader compilation looks a lot faster (removed shader cache for testing).

**Comment by asumagic** [comment] 2019-07-09 13:31
It does not happen on low graphic settings for me.

**Comment by daniel-schuermann** [comment] 2019-07-09 15:56
Does it still happen on higher settings? We fixed a couple of issues meanwhile, and maybe it was one of them :)

**Comment by asumagic** [comment] 2019-07-09 17:20
Actually I can't reproduce the issue in maximum settings on my RX580. I am using a mesa+ACO build built yesterday, neither in the shooting range nor in Havana I can see this happen (which I am guessing is where @lordkitsuna's screenshot was taken).
![Screenshot_20190709_191519](https://user-images.githubusercontent.com/8986152/60909272-1d242d80-a27e-11e9-96fe-38e1fe1fad92.png)
If I had to guess, either the bug accidentally got fixed either it is a vega specific bug. Could you check if you still get the issue, @lordkitsuna or @thunder1410?

Edit: Also, huge thanks for this - ACO makes OW a much more bearable experience. Random stutters are now completely gone for me.

**Comment by pendingchaos** [comment] 2019-07-09 18:04
@AsuMagic : I think @thunder1410 was also using a RX 580, so it's probably not vega specific

**Comment by varris1** [comment] 2019-07-09 20:01
Whatever caused the fog, it was fixed on my RX590.

![screenshot](https://user-images.githubusercontent.com/38386180/60919057-0e954080-a295-11e9-82c0-2d52a85ddade.png)

**Comment by ghost** [comment] 2019-07-09 21:06
So I compiled and installed this new mesa with ACO today.

I deleted `~/.cache/mesa_shader_cache`, `~/.cache/radv*`, and the DXVK state cache.

Overwatch ran fine for me, the shader compilation was extremely fast comparatively to starting fresh with LLVM. The game is normally unplayable and completely freezes constantly for several games. With this the stutter is much less and it's at a somewhat playable level pretty much from the start.

**Comment by daniel-schuermann** [comment] 2019-07-09 21:12
Thank you all for reporting! Seems, this issue was the same as one we fixed for some other game.

**Closed as completed by daniel-schuermann** 2019-07-09 21:12 UTC
