### ISSUE TITLE
Gentoo: (Nearly) all vulkan apps crashing immediately

### ISSUE THREAD

**Issue by SpookySkeletons** [daniel-schuermann/mesa#91] opened 2019-07-30 22:01 UTC
The introduction of the new vertex shader feature is now cashing nearly every vulkan application that compiles shaders.
Setting 'llvmvs' fixes the problem.

Mesa compiled COMMON_FLAGS="-O3 -pipe"

**System information:**
 - GPU: Mobile MXM WX7100
 - ACO version: 5c6077221dd0718f09c12fc1b1a6f65595416288

The only thing that seems to work is vkcube and BattleNet launcher login window before the main window appears, inheriting the framebuffer of the window's background, stalls for a few seconds, and then crashes.
The applications hang seemingly after compiling any vertex shader it looks like. I'm curious if the O3 is causing undefined behavior in ACO but I need to recompile...

**Comment by Bulbyzarr** [comment] 2019-07-31 05:09
I'm on Gentoo and i don't have your issue. All my Vulkan applications work correctly. And i build my system with "-O2 -pipe'

**Comment by daniel-schuermann** [comment] 2019-07-31 06:41
> I'm curious if the O3 is causing undefined behavior in ACO but I need to recompile...

I know what you mean, but O3 shouldn't cause undefined behavior (unless your compiler is broken). It can only cause undefined behavior to behave differently ;)
I'd be glad if you can try with O2. The difficult part might be to find out where it crashes... debug builds probably don't show this issue :/

**Comment by SpookySkeletons** [comment] 2019-08-01 00:14
Tried going as far as disabiling my ccache when I was wearing down.
It might be my LLVM being 9, I'm downgrading to version 8 to see if it changes because the ubuntu PPA is 8.

It's weird because ONLY the vertex shader is affected, I haven't had any issues up until this latest run of commits.

**Comment by SpookySkeletons** [comment] 2019-08-02 01:20
So I've got a proton log and it seems like a mixture of llvm AND aco both crash.
Must be an issue with mesa itself, was it updated to latest mesa git?
[steam-374320.log](https://github.com/daniel-schuermann/mesa/files/3459222/steam-374320.log)

Mesa seems to complain and drop some assembly it has trouble with.

**Comment by SpookySkeletons** [comment] 2019-08-02 02:34
If it helps any I am using DRI_PRIME=1 to offload vulkan to my amd gpu and display on my intel hd 4600.

**Comment by SpookySkeletons** [comment] 2019-08-02 04:03
I've disected the issue.
Commit d7c7cce761537ca7cc6dc9fc6568eaa72bfdf814 
breaks shaders on my setup.

**Comment by wispoffates** [comment] 2019-08-02 08:31
Interesting -03 appears to be fine on mine. AMD RX580+RADV maybe ffxiv through DXVK doesn't hit the issue.

I use the EGIT_REPO to build.
`
media-libs/mesa-9999::gentoo was built with the following:
USE="X classic d3d9 dri3 egl gallium gbm gles2 llvm lm_sensors vaapi vdpau vulkan wayland -debug -gles1 (-libglvnd) -opencl -osmesa -pax_kernel (-selinux) -test -unwind -valgrind -vulkan-overlay -xa -xvmc" ABI_X86="32 (64) (-x32)" VIDEO_CARDS="radeon radeonsi (-freedreno) -i915 -i965 -intel -iris (-lima) -nouveau (-panfrost) -r100 -r200 -r300 -r600 (-vc4) -virgl (-vivante) -vmware"

CFLAGS="-march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu"

CXXFLAGS="-march=native -O3 -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -fuse-linker-plugin -pipe -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu"

FEATURES="network-sandbox news preserve-libs usersandbox ipc-sandbox unknown-features-warn config-protect-if-modified unmerge-logs sandbox fixlafiles multilib-strict binpkg-dostrip ebuild-locks parallel-fetch binpkg-docompress userpriv sfperms userfetch pid-sandbox distlocks xattr usersync protect-owned merge-sync assume-digests unmerge-orphans strict binpkg-logs"
`

**Comment by daniel-schuermann** [comment] 2019-08-02 09:22
> So I've got a proton log and it seems like a mixture of llvm AND aco both crash.
Must be an issue with mesa itself, was it updated to latest mesa git?
steam-374320.log

Your log shows that some vertex shader breaks in the live-var analysis (l. 570ff). It is quite odd because it stops without any reason, the shader looks correct to me. Do you use some different stdlib? This pass uses `<set>` and variable %14 shouldn't make any troubles °°. Did you meanwhile test with -O2?

> Commit d7c7cce
breaks shaders on my setup.

This is not very surprising as you already said it works with llvmvs and also the shader that breaks is a vertex shader ;)
Would you be able to create a renderdoc capture with RADV_PERFTEST=llvmvs?

**Comment by SpookySkeletons** [comment] 2019-08-02 10:22
I've tested with O2, same result, originally I took the Gentoo wiki's advice about O3 maybe messing something up but it seems everything there is fine.

I'll get a capture for you when I'm back on my machine soon.

**Comment by SpookySkeletons** [comment] 2019-08-03 02:02
Yep, at least I know the capture includes the bad behavior. Crashes renderdoc on my card when I try to load it without llvmvs. Both frames included crash.

https://anonfile.com/Kaveb12bna/Captures_zip

**Comment by SpookySkeletons** [comment] 2019-08-03 02:15
Ultra weird behavior.
This mesa can actually randomly hard-lock my system.
Systemd starts sending SIGKILLs to my apps and can't sync the filesystem, happened while I was looking over the renderdoc and clicked the VS button in pipeline state with llvmvs set.

**Comment by daniel-schuermann** [comment] 2019-08-04 06:04
I cannot reproduce the behavior. Both captures open fine for me and I also don't get a single aco-related warning with valgrind. Would you checkout the current master branch, completely rebuild and see if the problem persists?

**Comment by SpookySkeletons** [comment] 2019-08-04 18:14
Ah, darn.
Well my last resort here is a gcc upgrade to 9.1.0, full system && world upgrade, and then a fresh kernel build. Let's see what happens.

**Comment by daniel-schuermann** [comment] 2019-08-05 07:09
FWIW, @BNieuwenhuizen could also reproduce this issue with Vega. I have no idea yet where this comes from, but maybe if you open the renderdoc capture with valgrind it might give us a hint?

**Comment by SpookySkeletons** [comment] 2019-08-07 06:11
Great news! The full rebuild cured my system's insanity... even if it took forever.
ACO launched apps no longer crash instantly!

Bad news though is that I think llvm is now slightly insane. I get crazy artifacting in BattleNet and Overwatch with the odd system hang too. It gets worse as I enable llvm features...
I'm going to emerge 10.0.0.9999 and see if everything resolves itself. I will report back one final time if all seems fine, otherwise will drop a RenderDoc.

I can also report that the new ACO vertex shader gives a very small bump to dark souls fps! I can push over 50 consistently looking up at the starting area god-rays now.

**Comment by SR-dude** [comment] 2019-08-08 22:49
> I can also report that the new ACO vertex shader gives a very small bump to dark souls fps! I can push over 50 consistently looking up at the starting area god-rays now.

Shall we close this then?

**Comment by SpookySkeletons** [comment] 2019-08-09 00:47
Grappling with a new issue. But all applications launch now. Closing issue.

**Comment by daniel-schuermann** [comment] 2019-08-09 05:39
As more people are affected by this bug, I'd like to keep it open.

**Comment by cwabbott0** [comment] 2019-08-14 10:02
It turns out that this was due to a GCC bug in GCC 8.3 which miscompiles `visit_load_input`. It might depend on the libstdc++ too, since `std::vector` is involved. See [this](https://godbolt.org/z/Wah15r) for a reduced test case which prints something different with -O2. It seems this is already fixed in GCC 8 trunk and GCC 9. GCC 9 is already out and GCC 8.4 is supposed to be released this year. If there are any major distro's with a broken GCC/libstdc++ version we might have to add a workaround, but otherwise we can hopefully drop this. I can reproduce it on Fedora 28, but that's already quite old now and not supported, so I just need to update.

**Comment by jerbmega** [comment] 2019-08-14 13:07
Can confirm that switching to a 9.x GCC profile solved the issue.

**Comment by pendingchaos** [comment] 2019-08-15 14:13
Should be worked around with aba8c9f0c7b734a4e661ca8745d1ee398d29bf26

**Closed as completed by pendingchaos** 2019-08-15 14:13 UTC
