### ISSUE TITLE
Dragon Quest XI - black sky corruption (aco-navi branch)

### ISSUE THREAD

**Issue by aqxa1** [daniel-schuermann/mesa#139] opened 2019-09-21 09:57 UTC
Dragon Quest XI has a corrupted sky bug in some circumstances with aco-navi branch. Game also randomly hangs, but I'll leave that to another issue report.

**Screenshots**
ACO:
![ACO screenshot](https://i.imgur.com/EpHSIr9.png)

LLVM:
![LLVM screenshot](https://i.imgur.com/H0wPwiA.png)

**RenderDoc capture:**
[Renderdoc capture](https://drive.google.com/open?id=1IKGwSnyAk_d81XhsXAop2121me-rrlmy)

**System information:**
 - GPU: MSI Evoke 5700 XT
 - ACO version: aco-navi 9d2b263f664

**Comment by aqxa1** [comment] 2019-09-22 03:46
Possible workaround is to set RADV_DEBUG=nohiz (looked to work at least once). But I haven't been able to reproduce again since it keeps GPU hanging on launch (even with CS disabled).

**Comment by aqxa1** [comment] 2019-10-04 04:25
Random hangs look to be fixed for this game with LLVM in latest mesa-git. If the ACO hangs were caused by the same issue, it might be worth rebasing against master.

**Comment by Venemo** [comment] 2019-10-04 10:49
Thanks for the bug report. Can you please test with the latest aco-navi branch? Also please make sure to add `RADV_DEBUG=nongg`.

**Comment by aqxa1** [comment] 2019-10-04 12:24
I tested it and the corrupted sky issue is fixed at least. It's still semi-randomly hanging, but it looks to be happening with LLVM as well. It did seem to work a few days ago, so it might be a kernel issue.

**Comment by aqxa1** [comment] 2019-10-05 06:25
Okay, so I played the game for a couple of hours with LLVM without any hangs, so the issue does now appear to be limited to ACO. I'm not sure why it was happening with LLVM before. All I can think is that I was accidentally forcing ACO on mainline mesa-git, but I would assume that isn't available for Navi yet anyway?

**Comment by Venemo** [comment] 2019-10-16 08:35
We're aware of the hang issue with Dragon Question XI but it is very likely to be unrelated to the shader compiler. We had a conversation yesterday about this, and the game hangs for us with LLVM as well.

**Comment by aqxa1** [comment] 2019-10-16 09:51
No worries, I'm the user that reported the issue on the mainline Mesa tracker, so I'm in agreement there. I do feel like ACO triggered the hangs more easily, but it might have just been a coincidence.

**Comment by Venemo** [comment] 2019-10-16 13:27
@aqxa1 If you have time for it, I'd appreciate if you could test on my latest aco-navi branch. There have been a good number of fixes since your last try.

**Comment by aqxa1** [comment] 2019-10-17 00:27
@Venemo Just tested it. No GPU hangs in *Sniflheim City*, but they remain in *Laguna di Gondalia*.

ACO has the same draw-in/pop-in rendering issues as LLVM as well:

![DQXI - rock from distance](https://i.imgur.com/DfIIy7I.jpg)

![DQXI - rock from close-up](https://i.imgur.com/8Ig2A63.jpg)

Note how the snow covering on the rock disappears as you get close to it.

**Comment by Venemo** [comment] 2019-10-22 16:14
@aqxa1 I had the opportunity to try Dragon Quest XI today. I couldn't reproduce the black sky problem. Unfortunately I haven't reached any area of the game with snow, so not sure about that one. Can you give us a save game with which to reproduce the issue?

**Comment by aqxa1** [comment] 2019-10-23 10:30
@Venemo The black sky problem has been fixed for a while. 

[dqxi-saves.zip](https://github.com/daniel-schuermann/mesa/files/3761814/dqxi-saves.zip)

One of the included saves is at "Sniflheim - Campsite" and should show the problem.

**Comment by pendingchaos** [comment] 2020-02-10 16:05
Closing this since the last issue (the snow glitch) seem to be resolved: https://gitlab.freedesktop.org/mesa/mesa/issues/2233

**Closed as completed by pendingchaos** 2020-02-10 16:05 UTC
Labels: Navi
